#! /usr/bin/bash

aws cognito-idp update-user-pool-client \
--user-pool-id us-east-1_MoMSmpk4y \
--client-id 59lu97to26ta6bttvlql3ro216 \
--callback-urls http://localhost:3000 \
--logout-urls http://localhost:3000 \
--supported-identity-providers Google \
--allowed-o-auth-flows-user-pool-client \
--allowed-o-auth-flows implicit \
--allowed-o-auth-scopes {email,openid,profile,aws.cognito.signin.user.admin}
