export const data = [
    "Just signed up for cruddur! Excited to see what everyone's posting about 🤩",
    "Can't believe how easy it is to post on cruddur! #gamechanger",
    "Feeling inspired today, so I'm sharing my favorite quote: 'The best way to predict the future is to invent it.' - Alan Kay",
    "Just discovered cruddur and already addicted 😍",
    "Anyone else having trouble coming up with a post for cruddur? 😅",
    "Just posted my first cruddur post! Feels good to get my thoughts out there 💭",
    "Happy Friday, cruddur fam! What are your weekend plans? 🎉",
    "Trying to come up with a witty post for cruddur... any ideas? 🤔",
    "Just realized I've spent the last hour scrolling through cruddur... oops 🙈",
    "Can't wait to see what everyone's posting on cruddur today! 🤗",
    "Feeling grateful for my friends and family today ❤️",
    "Just posted a new blog on cruddur! Check it out and let me know what you think 📝",
    "Trying to stay positive today, so I'm sharing my favorite emoji: 😊",
    "Happy Monday, cruddur fam! Let's make this week a good one 💪",
    "Just posted a new recipe on cruddur! Let me know if you try it out 🍴",
    "Feeling productive today, so I'm sharing my to-do list: ✅",
    "Just posted a new workout routine on cruddur! Let's get fit together 💪",
    "Can't believe how much I've already posted on cruddur... it's addicting! 😅",
    "Just posted a new DIY project on cruddur! Let me know if you try it out 🎨",
    "Feeling grateful for the little things today 🌻",
    "Just posted a new book review on cruddur! Let me know if you've read it 📚",
    "Trying to stay motivated today, so I'm sharing my favorite motivational quote: 'Believe you can and you're halfway there.' - Theodore Roosevelt",
    "Happy hump day, cruddur fam! We're halfway through the week 🐪",
    "Just posted a new travel guide on cruddur! Let me know if you've been there ✈️",
    "Feeling creative today, so I'm sharing my favorite art emoji: 🎨",
    "Just posted a new fashion look on cruddur! Let me know if you try any of the outfits 👗",
    "Trying to stay positive today, so I'm sharing my favorite positive quote: 'Positive anything is better than negative nothing.' - Elbert Hubbard",
    "Happy Tuesday, cruddur fam! Let's make today a good one 🌞",
    "Just posted a new makeup tutorial on cruddur! Let me know if you try it out 💄",
    "Feeling grateful for my health today 🙏",
    "Just posted a new playlist on cruddur! Let me know if you like the songs 🎶",
    "Trying to stay focused today, so I'm sharing my favorite productivity emoji: 📈",
    "Happy Thursday, cruddur fam! Almost the weekend 🎉",
    "Just posted a new podcast episode on cruddur! Let me know if you listen 🎙️",
    "Feeling motivated today, so I'm sharing my favorite motivational emoji: 💪",
    "Just posted a new movie review on cruddur! Let me know if you've seen it 🎥",
    "Trying to stay calm today, so I'm sharing my favorite relaxation emoji: 🧘",
    "Happy Wednesday, cruddur fam! We're halfway through the week 🌟",
    "Just posted a new art project on cruddur! Let me know if you try it out 🎨",
    "Feeling grateful for my job today 🙌",
    "Just posted a new podcast recommendation on cruddur! Let me know if you listen 🎧",
    "Trying to stay positive today, so I'm sharing my favorite positive emoji: 😁",
    "Happy Friday eve, cruddur fam! One more day until the weekend 🎉",
    "Just posted a new poetry collection on cruddur! Let me know if you like the poems 📖",
    "Feeling inspired today, so I'm sharing my favorite inspirational quote: 'You miss 100% of the shots you don't take.' - Wayne Gretzky",
    "Just posted a new recipe video on cruddur! Let me know if you try it out 🍳",
    "Trying to stay focused today, so I'm sharing my favorite focus emoji: 🔍",
    "Happy Sunday, cruddur fam! Let's make today a good one 🌞",
    "Just posted a new gardening tutorial on cruddur! Let me know if you try it out 🌻",
    "Feeling grateful for my pets today 🐾"
]
